server:
  port: 10002
spring:
  application:
    name: eureka-bank-client
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tom.eurekaclient.model
logging:
  level: warn